[default]
DEBUG = false
SQLALCHEMY_DATABASE_URI = 'sqlite+pysqlite:///app.db'
SQLALCHEMY_TRACK_MODIFICATIONS = false
INSTALLED_APPS = [
    'app.ext.db:init_app',
    'app.ext.migrate:init_app',
    'app.ext.cli:init_app',
    'app.ext.login:init_app',
    'app.ext.site:init_app',
    'app.ext.log:init_app',
]


[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite+pysqlite:///app.db'
SQLALCHEMY_TRACK_MODIFICATIONS = false
INSTALLED_APPS = [
    'app.ext.db:init_app',
    'app.ext.migrate:init_app',
    'app.ext.cli:init_app',
    'app.ext.login:init_app',
    'app.ext.site:init_app',
    'app.ext.log:init_app',
    'app.ext.bootstrap:init_app',
]
POST_PER_PAGE = 3

[production]